// ============================================================================
// CORRECTED DOPRI-INSPIRED ADAPTIVE PIECEWISE POLYNOMIAL
// ============================================================================
//
// FIXES: Incorrect range [-4, 3] → Correct full bfloat16 range
//
// Regions:
//   |x| < 0.5: Taylor series (avoids polynomial constant term issue)
//   [-4, -0.5]: DOPRI adaptive polynomial (negative core, normal outputs)
//   [0.5, 2.78125]: DOPRI adaptive polynomial (positive core)
//   x < -4: Asymptotic/LUT via gelu_negative_tail() (subnormal outputs)
//   x >= 2.78125: Identity (saturation)
//
// Generated by generate_dopri_coeffs_v2.py
// ============================================================================

/**
 * @brief DOPRI Fixed Deg5 Seg12
 *
 * CORRECTED DOPRI implementation for full bfloat16 range:
 * - Near-zero (|x| < 0.5): Taylor series GELU(x) ≈ 0.5x + 0.3989x³
 * - Negative core [-4.0, -0.5]: DOPRI Deg5 x 12seg
 * - Positive core [0.5, 2.78125]: DOPRI Deg5 x 12seg
 * - Deep tail (x < -4.0): Uses gelu_negative_tail()
 * - Saturation (x >= 2.78125): Identity
 */
std::bfloat16_t gelu_dopri_fixed_deg5_seg12(std::bfloat16_t x_bf16) {
    float x = static_cast<float>(x_bf16);

    // Positive saturation
    if (x >= 2.78125f) {
        return static_cast<std::bfloat16_t>(x);
    }

    // Deep negative tail
    if (x < -4.0f) {
        return static_cast<std::bfloat16_t>(gelu_negative_tail(x));
    }

    // Near-zero region: Taylor series avoids polynomial constant term issue
    if (std::abs(x) < 0.5f) {
        // GELU(x) ≈ 0.5x + cx³ for small x
        // Coefficients from Taylor expansion of x·Φ(x)
        constexpr float c3 = 0.3989422804f / 6.0f;  // (1/√(2π))/6
        return static_cast<std::bfloat16_t>(0.5f * x + c3 * x * x * x);
    }

    // Negative region: [-4.0, -0.5]
    if (x < -0.5f) {
        constexpr float neg_breakpoints[] = {
            -4.00000000f, -3.47375473f, -2.99278810f, -2.60730806f, -2.23529484f,
            -1.69977990f, -1.39074640f, -1.09976582f, -0.81086881f, -0.70692788f,
            -0.61583184f, -0.53611517f, -0.50000000f
        };

        constexpr float neg_coeffs[12][6] = {
            { -9.605446201066e-01f, -1.108224222601e+00f, -5.159534403915e-01f, -1.210873212629e-01f, -1.431611449505e-02f, -6.817508227028e-04f },
            { -9.981652786932e-01f, -1.151447117601e+00f, -5.345525236759e-01f, -1.246304194722e-01f, -1.456480844237e-02f, -6.809675015695e-04f },
            { -5.445252041811e-01f, -3.895458064785e-01f, -2.215016183084e-02f, 4.785510383273e-02f, 1.449657521951e-02f, 1.279610072847e-03f },
            { -7.487968405874e-02f, 5.100813797162e-01f, 6.679792028509e-01f, 3.128789702152e-01f, 6.544439177402e-02f, 5.201906627214e-03f },
            { 1.414131801894e-01f, 9.878608037965e-01f, 1.090772570490e+00f, 5.002371717037e-01f, 1.070237174313e-01f, 8.898881908541e-03f },
            { 7.560413726679e-02f, 7.921981295693e-01f, 8.576476540135e-01f, 3.611051234863e-01f, 6.543176813729e-02f, 3.916839568921e-03f },
            { 2.170094044398e-02f, 5.995822410773e-01f, 5.816163598495e-01f, 1.627996151279e-01f, -5.989286619873e-03f, -6.399380585217e-03f },
            { 2.537251905252e-03f, 5.141083750442e-01f, 4.285771897017e-01f, 2.528349721130e-02f, -6.800913873453e-02f, -1.763131588749e-02f },
            { 5.921596149047e-05f, 4.998783500912e-01f, 3.958349187328e-01f, -1.245773905641e-02f, -8.980712239848e-02f, -2.267893125069e-02f },
            { -1.254557650771e-04f, 4.985997438180e-01f, 3.922911134378e-01f, -1.737271485094e-02f, -9.321828900784e-02f, -2.362672870694e-02f },
            { -1.141244066996e-04f, 4.986989894809e-01f, 3.926371448848e-01f, -1.677194991035e-02f, -9.269862426344e-02f, -2.344747698636e-02f },
            { -8.197402747532e-05f, 4.989944995850e-01f, 3.937242601910e-01f, -1.477112555968e-02f, -9.085626194590e-02f, -2.276848274935e-02f },
        };

        int seg = 0;
        for (int i = 1; i < 12; i++) {
            if (x >= neg_breakpoints[i]) seg = i;
        }

        float result = neg_coeffs[seg][5];
        result = result * x + neg_coeffs[seg][4];
        result = result * x + neg_coeffs[seg][3];
        result = result * x + neg_coeffs[seg][2];
        result = result * x + neg_coeffs[seg][1];
        result = result * x + neg_coeffs[seg][0];
        return static_cast<std::bfloat16_t>(result);
    }

    // Positive region: [0.5, 2.78125]
    constexpr float pos_breakpoints[] = {
        0.50000000f, 0.60192041f, 0.66732192f, 0.74860918f, 0.84041737f,
        0.95019863f, 1.09176739f, 1.28739316f, 1.49410194f, 1.72570219f,
        2.05798110f, 2.35333388f, 2.78125000f
    };

    constexpr float pos_coeffs[12][6] = {
        { -1.000030002396e-04f, 5.011757332363e-01f, 3.930814721205e-01f, 1.598439850921e-02f, -9.200103540686e-02f, 2.320044439090e-02f },
        { -1.317201841245e-04f, 5.014485078715e-01f, 3.921424981351e-01f, 1.760150877015e-02f, -9.339434713913e-02f, 2.368090248724e-02f },
        { -7.872307012159e-05f, 5.010608831064e-01f, 3.932768928070e-01f, 1.594106019277e-02f, -9.217871977516e-02f, 2.332479226472e-02f },
        { 2.365852713342e-04f, 4.989810035683e-01f, 3.987684309114e-01f, 8.686371518351e-03f, -8.738339565764e-02f, 2.205601155767e-02f },
        { 1.330985190280e-03f, 4.925461828377e-01f, 4.139140763711e-01f, -9.151615846909e-03f, -7.687065648946e-02f, 1.957577817494e-02f },
        { 4.808904969540e-03f, 4.744979451308e-01f, 4.514124489363e-01f, -4.814313694935e-02f, -5.657911639556e-02f, 1.534770038281e-02f },
        { 1.599723505518e-02f, 4.241384980643e-01f, 5.421942669200e-01f, -1.300728442449e-01f, -1.956056838410e-02f, 8.648360317092e-03f },
        { 4.400566551773e-02f, 3.159741750072e-01f, 7.095106239051e-01f, -2.596616422707e-01f, 3.069392481975e-02f, 8.419312458459e-04f },
        { 9.142188669233e-02f, 1.577660043854e-01f, 9.209182528332e-01f, -4.010826151621e-01f, 7.805358054368e-02f, -5.509819190488e-03f },
        { 1.421132403823e-01f, 1.042630271535e-02f, 1.092435373274e+00f, -5.010367048365e-01f, 1.072138303330e-01f, -8.916726544023e-03f },
        { 8.484970331470e-02f, 1.449914976653e-01f, 9.659676944152e-01f, -4.416191955357e-01f, 9.325910078645e-02f, -7.606119732537e-03f },
        { -2.353039575592e-01f, 8.125752414575e-01f, 4.084951602047e-01f, -2.085773482577e-01f, 4.448963389661e-02f, -3.518549196840e-03f },
    };

    int seg = 0;
    for (int i = 1; i < 12; i++) {
        if (x >= pos_breakpoints[i]) seg = i;
    }

    float result = pos_coeffs[seg][5];
    result = result * x + pos_coeffs[seg][4];
    result = result * x + pos_coeffs[seg][3];
    result = result * x + pos_coeffs[seg][2];
    result = result * x + pos_coeffs[seg][1];
    result = result * x + pos_coeffs[seg][0];
    return static_cast<std::bfloat16_t>(result);
}
